signing.keyId=
signing.password=
signing.secretKeyRingFile=

# Set `mavenCentralUsername` and `mavenCentralPassword` in `~/.gradle/gradle.properties` as plug-in
# io.github.sgtsilvio.gradle.maven-central-publishing does not pick up values in `gradle.local.properties`.
