package com.squins.kwmdsl

import org.apache.wicket.Component
import org.apache.wicket.MarkupContainer

/**
 * Markup generated by using a builder. There are 2 variants: root markup contains the full markup text and children (possibly none), and child markup contains only children (possibly none). The Wicket component hierarchy built with the markup builder matches the child markup hierarchy.
 *
 * @param TSupplier the markup container type having the properties and functions to get the Wicket components.
 * @param children child elements that are associated with Wicket components that are to be retrieved during the addition of the root markup to the markup container.
 */
abstract class Markup<TSupplier : MarkupContainer> internal constructor(
    internal val children: List<ChildMarkup<TSupplier>>,
) {
    /**
     * Adds the hierarchy of Wicket components, retrieved using the suppliers, to [container]. The suppliers will be invoked on [supplier].
     *
     * If a child Wicket component added to `container` is itself a [MarkupContainer], then the children of the child are also added to the child, recursively.
     *
     * @param supplier the supplier having the supplier functions or properties used to retrieve the components.
     * @param container the container to which the add the child components.
     */
    internal fun addTo(supplier: TSupplier, container: MarkupContainer) {
        children.forEach { childMarkup ->
            val component = childMarkup.retrieveComponent(supplier)
            container.add(component)
            addChildMarkupToComponentIfContainer(childMarkup, supplier, component)
        }
    }

    /**
     * Add the child Wicket components of [childMarkup] to [component], if `component` itself is a [MarkupContainer].
     *
     * @param childMarkup the child markup of which to add the children to `component`, if `component` is a `MarkupContainer`.
     * @param supplier the supplier having the supplier functions or properties used to retrieve the components.
     * @param component the Wicket component associated with `childMarkup`.
     */
    internal fun addChildMarkupToComponentIfContainer(
        childMarkup: ChildMarkup<TSupplier>,
        supplier: TSupplier,
        component: Component
    ) {
        if (component is MarkupContainer) {
            childMarkup.addTo(supplier, component)
        }
    }

    /**
     * Append the canonical, human-readable presentation of the Wicket component hierarchy of this markup to [builder], indenting with [indentSize].
     *
     * @param builder the builder to append the representation to.
     * @param indentSize the number of spaces to indent the lines with.
     */
    internal fun getComponentHierarchyString(builder: StringBuilder, indentSize: Int) {
        val indent = (0 until indentSize).joinToString("") { "    " }
        children.sortedBy { it.expectedWicketId }.forEach { child ->
            builder
                .append(indent)
                .append(child.expectedWicketId)
                .append(System.lineSeparator())
            child.getComponentHierarchyString(builder, indentSize + 1)
        }
    }
}
